add sorting for candidate quizzes
BaiasPaul/QuizApp pull request #33
Opened 2020-04-08 08:29 UTC by BaiasPaul

add sorting for candidate quizzes
Jira: https://jira.evozon.com/browse/PHPTRAININ-265

2020-04-08 12:40 UTC, victortodoran commented on src/Controller/QuizInstanceController.php
>          $totalResults = (int)$this->quizInstanceService->getEntityNumberOfPagesByField(QuizTemplate::class, []);
Law of Demeter.

2020-04-08 12:41 UTC, victortodoran commented on src/Controller/QuizInstanceController.php
>          }
Extract logic that builds filter into separate method.

2020-04-08 12:42 UTC, victortodoran commented on src/Controller/QuizInstanceController.php
why not pass the filter to the template? It already has the orderBy and sortType grouped together.

2020-04-08 12:43 UTC, victortodoran commented on views/candidate-quiz-listing.phtml
>              <tr>
too much logic to follow in this <th> please make it easier to understand.

2020-04-14 08:01 UTC, calinpristavu requested changes

2020-04-14 08:01 UTC, calinpristavu commented on src/Controller/QuizInstanceController.php
> +            'url' => $this->urlBuilder,
inject UrlBuilder from the framework into all templates

2020-04-15 12:00 UTC, merged